[package]
name = "hd44780u"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2"
nalgebra = { version = "0.31", default-features = false, features = ["libm"] }