[target.thumbv6m-none-eabi]
runner = "probe-run --chip RP2040"
rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "inline-threshold=5",
    "-C", "no-vectorize-loops",
]

[build]
# Set the default target to match the Cortex-M0+ in the RP2040
target = "thumbv6m-none-eabi"

[test]
# Set the default target to match the Cortex-M0+ in the RP2040
target = "thumbv6m-none-eabi"
